package me.serenityline.api.finance.calendar;

public enum FinanceCalendarMovementType {
    PERSISTED_TRANSACTION,
    PROJECTED_RECURRING_TRANSACTION,
    TECHNICAL_CREDIT_CARD_CHARGE_FROM_PERSISTED_TRANSACTION,
    TECHNICAL_CREDIT_CARD_CHARGE_FROM_PROJECTED_RECURRING_TRANSACTION
}