package me.serenityline.api.email.outbox.entity;

public enum EmailOutboxType {
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    EMAIL_CHANGE_CONFIRMATION,
    LOGIN_2FA_CODE,
    EMAIL_2FA_ENABLE_CONFIRMATION,
    EMAIL_2FA_DISABLE_CONFIRMATION,
    EMAIL_CHANGE_NOTIFICATION,
    TRANSACTION_REMINDER,
    RECURRING_TRANSACTION_REMINDER,
    USER_INVITATION,
    GENERIC
}